In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
%matplotlib inline

In [2]:
TRAIN_CSV_PATH = "data/train.csv"
TRAIN_ADD_CSV_PATH = "data/train_add.csv"
TEST_CSV_PATH = "data/test.csv"
ADD_2014_CSV_PATH = "data/2014_add.csv"
STADIUM_CSV_PATH = "data/stadium.csv"
CONDITION_CSV_PATH = "data/condition.csv"
CONDITION_ADD_CSV_PATH = "data/condition_add.csv"

In [3]:
df_train = pd.read_csv(TRAIN_CSV_PATH)
df_train.head()

,id,y,year,stage,match,gameday,time,home,away,stadium,tv
0,13994,18250,2012,Ｊ１,第１節第１日,03/10(土),14:04,ベガルタ仙台,鹿島アントラーズ,ユアテックスタジアム仙台,スカパー／ｅ２／スカパー光／ＮＨＫ総合
1,13995,24316,2012,Ｊ１,第１節第１日,03/10(土),14:04,名古屋グランパス,清水エスパルス,豊田スタジアム,スカパー／ｅ２／スカパー光（Ｊ ＳＰＯＲＴＳ ４）／ＮＨＫ名古屋
2,13996,17066,2012,Ｊ１,第１節第１日,03/10(土),14:04,ガンバ大阪,ヴィッセル神戸,万博記念競技場,スカパー／ｅ２／スカパー光（Ｊ ＳＰＯＲＴＳ １）／ＮＨＫ大阪
3,13997,29603,2012,Ｊ１,第１節第１日,03/10(土),14:06,サンフレッチェ広島,浦和レッズ,エディオンスタジアム広島,スカパー／ｅ２／スカパー光／ＮＨＫ広島
4,13998,25353,2012,Ｊ１,第１節第１日,03/10(土),14:04,コンサドーレ札幌,ジュビロ磐田,札幌ドーム,スカパー／ｅ２／スカパー光（スカイ・Ａ ｓｐｏｒｔｓ＋）／ＮＨＫ札幌

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1721 entries, 0 to 1720
Data columns (total 11 columns):
id         1721 non-null int64
y          1721 non-null int64
year       1721 non-null int64
stage      1721 non-null object
match      1721 non-null object
gameday    1721 non-null object
time       1721 non-null object
home       1721 non-null object
away       1721 non-null object
stadium    1721 non-null object
tv         1721 non-null object
dtypes: int64(3), object(8)
memory usage: 148.0+ KB

In [6]:
df_train_add = pd.read_csv(TRAIN_ADD_CSV_PATH)
df_train_add.head()

,id,y,year,stage,match,gameday,time,home,away,stadium,tv
0,14003,19010,2012,Ｊ１,第２節第１日,03/17(土),14:04,鹿島アントラーズ,川崎フロンターレ,県立カシマサッカースタジアム,スカパー／ｅ２／スカパー光／ＮＨＫ水戸
1,14020,15072,2012,Ｊ１,第３節第２日,03/25(日),19:03,ガンバ大阪,ジュビロ磐田,万博記念競技場,スカパー／ｅ２／スカパー光
2,14023,25743,2012,Ｊ１,第４節第１日,03/31(土),15:03,浦和レッズ,川崎フロンターレ,埼玉スタジアム２００２,スカパー／ｅ２／スカパー光／テレ玉
3,14076,24183,2012,Ｊ１,第１０節第１日,05/06(日),13:03,横浜Ｆ・マリノス,コンサドーレ札幌,日産スタジアム,スカパー／ｅ２／スカパー光
4,14081,20512,2012,Ｊ１,第１０節第１日,05/06(日),17:03,名古屋グランパス,川崎フロンターレ,豊田スタジアム,スカパー／ｅ２／スカパー光（Ｊ ＳＰＯＲＴＳ ４）／名古屋テレビ（録）

In [7]:
df_train_add.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 11 columns):
id         232 non-null int64
y          232 non-null int64
year       232 non-null int64
stage      232 non-null object
match      232 non-null object
gameday    232 non-null object
time       232 non-null object
home       232 non-null object
away       232 non-null object
stadium    232 non-null object
tv         232 non-null object
dtypes: int64(3), object(8)
memory usage: 20.0+ KB

In [8]:
df_add_2014 = pd.read_csv(ADD_2014_CSV_PATH)
df_add_2014.head()

,id,year,stage,match,gameday,time,home,away,stadium,tv
0,15826,2014,Ｊ１,第１８節第１日,08/02(土),18:34,ＦＣ東京,清水エスパルス,味の素スタジアム,スカパー！／スカパー！プレミアムサービス／ＴＯＫＹＯ ＭＸ
1,15835,2014,Ｊ１,第１９節第１日,08/09(土),18:04,清水エスパルス,徳島ヴォルティス,ＩＡＩスタジアム日本平,スカパー！／スカパー！プレミアムサービス
2,15837,2014,Ｊ１,第１９節第１日,08/09(土),19:04,セレッソ大阪,ＦＣ東京,ヤンマースタジアム長居,スカパー！／スカパー！プレミアムサービス
3,15839,2014,Ｊ１,第１９節第２日,08/11(月),19:04,サンフレッチェ広島,サガン鳥栖,エディオンスタジアム広島,スカパー！／スカパー！プレミアムサービス
4,15872,2014,Ｊ１,第２３節第１日,09/13(土),19:04,アルビレックス新潟,ベガルタ仙台,デンカビッグスワンスタジアム,スカパー！／スカパー！プレミアムサービス

In [9]:
df_add_2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
id         38 non-null int64
year       38 non-null int64
stage      38 non-null object
match      38 non-null object
gameday    38 non-null object
time       38 non-null object
home       38 non-null object
away       38 non-null object
stadium    38 non-null object
tv         38 non-null object
dtypes: int64(2), object(8)
memory usage: 3.0+ KB

In [10]:
df_stadium = pd.read_csv(STADIUM_CSV_PATH)
df_stadium.head()

          name           address   capa
0  名古屋市瑞穂陸上競技場  愛知県名古屋市瑞穂区山下通5-1  20000
1      豊田スタジアム      愛知県豊田市千石町7-2  40000
2    フクダ電子アリーナ  千葉県千葉市中央区川崎町1-20  18500
3     日立柏サッカー場    千葉県柏市日立台1-2-50  15349
4   ニンジニアスタジアム      愛媛県松山市上野町乙46  15576

In [11]:
df_stadium.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 3 columns):
name       59 non-null object
address    59 non-null object
capa       59 non-null int64
dtypes: int64(1), object(2)
memory usage: 1.5+ KB

In [12]:
df_condition = pd.read_csv(CONDITION_CSV_PATH)
df_condition.head()

,id,home_score,away_score,weather,temperature,humidity,referee,home_team,home_01,home_02,...,away_02,away_03,away_04,away_05,away_06,away_07,away_08,away_09,away_10,away_11
0,13994,1,0,雨,3.8,66%,木村 博之,ベガルタ仙台,林 卓人,菅井 直樹,...,新井場 徹,岩政 大樹,中田 浩二,アレックス,青木 剛,増田 誓志,小笠原 満男,本山 雅志,大迫 勇也,ジュニーニョ
1,13995,1,0,屋内,12.4,43%,西村 雄一,名古屋グランパス,楢﨑 正剛,田中 隼磨,...,吉田 豊,岩下 敬輔,カルフィン ヨン ア ピン,李 記帝,村松 大輔,河井 陽介,枝村 匠馬,高木 俊幸,アレックス,大前 元紀
2,13996,2,3,晴一時雨,11.3,41%,高山 啓義,ガンバ大阪,藤ヶ谷 陽介,加地 亮,...,近藤 岳登,北本 久仁衛,伊野波 雅彦,相馬 崇人,三原 雅俊,田中 英雄,野沢 拓也,橋本 英郎,森岡 亮太,大久保 嘉人
3,13997,1,0,曇一時雨のち晴,11.4,52%,松尾 一,サンフレッチェ広島,西川 周作,森脇 良太,...,濱田 水輝,阿部 勇樹,槙野 智章,平川 忠亮,鈴木 啓太,山田 直輝,梅崎 司,柏木 陽介,原口 元気,田中 達也
4,13998,0,0,屋内,22.5,32%,廣瀬 格,コンサドーレ札幌,李 昊乗,高木 純平,...,駒野 友一,チョ ビョングク,藤田 義明,山本 脩斗,小林 裕紀,山本 康裕,山田 大記,松浦 拓弥,菅沼 実,前田 遼一

In [13]:
df_condition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2034 entries, 0 to 2033
Data columns (total 31 columns):
id             2034 non-null int64
home_score     2034 non-null int64
away_score     2034 non-null int64
weather        2034 non-null object
temperature    2034 non-null float64
humidity       2034 non-null object
referee        2034 non-null object
home_team      2034 non-null object
home_01        2034 non-null object
home_02        2034 non-null object
home_03        2034 non-null object
home_04        2034 non-null object
home_05        2034 non-null object
home_06        2034 non-null object
home_07        2034 non-null object
home_08        2034 non-null object
home_09        2034 non-null object
home_10        2034 non-null object
home_11        2034 non-null object
away_team      2034 non-null object
away_01        2034 non-null object
away_02        2034 non-null object
away_03        2034 non-null object
away_04        2034 non-null object
away_05        2034 non-null object
away_06        2034 non-null object
away_07        2034 non-null object
away_08        2034 non-null object
away_09        2034 non-null object
away_10        2034 non-null object
away_11        2034 non-null object
dtypes: float64(1), int64(3), object(27)
memory usage: 492.7+ KB

In [14]:
df_condition_add = pd.read_csv(CONDITION_ADD_CSV_PATH)
df_condition_add.head()

,id,home_score,away_score,weather,temperature,humidity,referee,home_team,home_01,home_02,...,away_02,away_03,away_04,away_05,away_06,away_07,away_08,away_09,away_10,away_11
0,14003,0,1,雨,13.3,86%,西村 雄一,鹿島アントラーズ,曽ヶ端 準,新井場 徹,...,實藤 友紀,ジェシ,森下 俊,小宮山 尊信,中村 憲剛,柴崎 晃誠,田坂 祐介,山瀬 功治,レナト,小松 塁
1,14020,1,2,曇,4.6,56%,家本 政明,ガンバ大阪,藤ヶ谷 陽介,加地 亮,...,駒野 友一,チョ ビョングク,藤田 義明,金沢 浄,小林 裕紀,山本 康裕,山田 大記,松浦 拓弥,菅沼 実,前田 遼一
2,14023,1,1,雨,10.0,65%,家本 政明,浦和レッズ,加藤 順大,坪井 慶介,...,田中 裕介,ジェシ,森下 俊,小宮山 尊信,中村 憲剛,柴崎 晃誠,田坂 祐介,山瀬 功治,レナト,小松 塁
3,14076,2,1,晴,27.9,47%,今村 義朗,横浜Ｆ・マリノス,飯倉 大樹,小林 祐三,...,日高 拓磨,ジェイド ノース,櫛引 一紀,岩沼 俊介,河合 竜二,宮澤 裕樹,古田 寛幸,近藤 祐介,高木 純平,前田 俊介
4,14081,2,3,晴,19.0,48%,吉田 寿光,名古屋グランパス,楢﨑 正剛,石櫃 洋祐,...,田中 裕介,井川 祐輔,森下 俊,登里 享平,稲本 潤一,中村 憲剛,大島 僚太,田坂 祐介,楠神 順平,矢島 卓郎

In [15]:
df_condition_add.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 31 columns):
id             270 non-null int64
home_score     270 non-null int64
away_score     270 non-null int64
weather        270 non-null object
temperature    270 non-null float64
humidity       270 non-null object
referee        270 non-null object
home_team      270 non-null object
home_01        270 non-null object
home_02        270 non-null object
home_03        270 non-null object
home_04        270 non-null object
home_05        270 non-null object
home_06        270 non-null object
home_07        270 non-null object
home_08        270 non-null object
home_09        270 non-null object
home_10        270 non-null object
home_11        270 non-null object
away_team      270 non-null object
away_01        270 non-null object
away_02        270 non-null object
away_03        270 non-null object
away_04        270 non-null object
away_05        270 non-null object
away_06        270 non-null object
away_07        270 non-null object
away_08        270 non-null object
away_09        270 non-null object
away_10        270 non-null object
away_11        270 non-null object
dtypes: float64(1), int64(3), object(27)
memory usage: 65.5+ KB